### ISSUE TITLE
Allow Scaling with_threads() w/ # CPUs

### ISSUE THREAD

**Issue by dpc** [NfNitLoop/pipeliner#1]
Could `with_threads(0)` mean number of CPUs in the system? That's actually most typical usage.

Any chance of getting ordered output? Only then it's a plug-and-play solution for everyone.

**Comment by nabijaczleweli** [comment]
> Could `with_threads(0)` mean number of CPUs in the system?

Heh, that was my first thought when reading that comment, too. I'll just submit a PR and see how it plays out.

**Comment by NfNitLoop** [comment]
Hi you two!

Thanks for the feedback. Glad to see people interested in my little library. Unfortunately GitHub wasn't sending me notifications or I missed them, so I'm only seeing this now.

I'm not fond of having special/"magic" meaning assigned to 0.  What about a new method like `with_cpu_threads(1)` which would let you schedule N threads per CPU?

**Comment by NfNitLoop** [comment]
> Any chance of getting ordered output?

I'll look into it. Since I'm just using MPSC channels to collect results back into an iterator, it might be a significant rewrite (or parallel implementation) to be able to safely block (with O(1) memory) on the next item in order.  Let's track that over in #4.

**Comment by dpc** [comment]
The ordered output is actually quite tricky to do, without a possibility of deadlocks / unbound memory, in face of all thread pools possibly taking a random amount of time.

**Comment by NfNitLoop** [comment]
The more I think about this, the more I think I prefer going this route:

~~~rust
extern crate num_cpus;

// ...

let cpus = num_cpus.get();
let results = my_iterator.with_threads(cpus).map(whatever);
~~~

It's not hard at all to get the number of CPUs yourself (and maybe you want to do something like `* 2`, or add a floor or ceiling to your thread count anyway.)

But I could do this to make it more clear:

 - [ ] Update docs to include a `num_cpus` example.

**Comment by NfNitLoop** [comment]
Closing this as "won't fix".

Documenting how to use other crates in my crate seems weird.  Anyone who googles "[rust number cpus][1]" is going to find [num_cpus] which has all the docs you need. :) 

[1]: http://lmgtfy.com/?q=rust+number+cpus
[num_cpus]: https://crates.io/crates/num_cpus

Some good news, though. [ordered output] should be live this weekend.

[ordered output]: https://github.com/NfNitLoop/pipeliner/issues/4
